routes/web.php
<?php

use App\Http\Controllers\CartController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use App\Mail\OrderShippedEmail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-email', function(){
    $user = auth()->user();
    \Mail::to($user->email)->send(new OrderShippedEmail($user));
});

Route::get('/', [PublicController::class, 'index']);
Route::get('/product-details/{product}', [PublicController::class, 'singleProduct'])->name('product-details');
Route::post('/comments/{id}', [CommentController::class, 'store'])->name('comments.store');
Route::get('products/{product}/add-to-cart', [CartController::class, 'add'])->name('add_to_cart');
Route::get('transaction/create', [TransactionController::class, 'create']);
Route::post('payment-success', [TransactionController::class, 'success']);
Route::post('payment-failed', [TransactionController::class, 'fail']);

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    Route::get('/home', function () {

        // sendSMS('01751906710', 'Hello, Greetings from Pondit.');

        return view('backend.home');
    })->name('home');

    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    // Category
    Route::get('categories/export/', [CategoryController::class, 'export'])->name('categories.export');
    Route::get('categories/pdf/', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');
    Route::get('/trashed-categories', [CategoryController::class, 'trash'])
        ->name('categories.trashed')->middleware('age_checker');
    Route::get('/trashed-categories/{category}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/trashed-categories/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);
   
    //Product
    Route::resource('products', ProductController::class);
    
    // User
    Route::get('users/export/', [UserController::class, 'export'])->name('users.export');
    Route::get('users/pdf/', [UserController::class, 'downloadPdf'])->name('users.pdf');
    Route::get('/trashed-users', [UserController::class, 'trash'])
        ->name('users.trashed')->middleware('age_checker');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    Route::get('/users/edit-profile', [ProfileController::class, 'edit'])->name('users.profile.edit');

    Route::patch('/users/update-profile', [ProfileController::class, 'update'])->name('users.profile.update');

    Route::resource('users', UserController::class)->except(
        ['create', 'store']
    );

});

app/View/Components/FrontendLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FrontendLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('frontend.layouts.master');
    }
}

resources/views/frontend/index.blade.php
<x-frontend-layout>

    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

        @foreach ($products as $product)
            <x-frontend.product-card :product="$product"/>
        @endforeach

    </div>
</x-frontend-layout>

resources/views/frontend/single-product.blade.php
<x-frontend-layout>
    <div class="row">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <img class="card-img-top" src="{{ asset('storage/products/'.$product->image) }}" height="180" alt="..." />
                <!-- Product details-->
            </div>
        </div>

        <div class="col-md-8 mb-5">
            <div class="card h-100">
                <!-- Sale badge-->
                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>

                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">
                            {{ $product->title }}
                        </h5>
                        <p> {{ $product->description }}</p>
                        <!-- Product reviews-->
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                            <div class="bi-star-fill"></div>
                        </div>
                        <!-- Product price-->
                        <span class="text-muted text-decoration-line-through">TK {{ $product->price }}</span>
                        TK {{ $product->price - $product->discount  }}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ route('add_to_cart', ['product'=>$product->id]) }}">Add to cart</a></div>

                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ url('transaction/create') }}">Buy</a></div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    Comments:

    <ul>
        @foreach ($product->comments as $comment)
        <li> {{ $comment->body }}
            By - {{ $comment->createdBy->name ?? 'Anonymous' }}
            At {{ $comment->created_at->diffForHumans() }}
        </li>
        @endforeach
    </ul>

    @auth
    <form action="{{ route('comments.store', ['id' => $product->id]) }}" method="post">
        @csrf
        <textarea name="body" class="form-control"></textarea>
        <button type="submit">
            Save
        </button>
    </form>
    @endauth

    @push('css')
        <style>
            body{
                background: skyblue;
            }
        </style>
    @endpush

</x-frontend-layout>