routes/web.php
<?php

use App\Http\Controllers\CartController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use App\Mail\OrderShippedEmail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-email', function(){
    $user = auth()->user();
    \Mail::to($user->email)->send(new OrderShippedEmail($user));
});

Route::get('/', [PublicController::class, 'index']);
Route::get('/product-details/{product}', [PublicController::class, 'singleProduct'])->name('product-details');
Route::post('/comments/{id}', [CommentController::class, 'store'])->name('comments.store');
Route::get('products/{product}/add-to-cart', [CartController::class, 'add'])->name('add_to_cart');
Route::get('transaction/create', [TransactionController::class, 'create']);
Route::post('payment-success', [TransactionController::class, 'success']);
Route::post('payment-failed', [TransactionController::class, 'fail']);

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    Route::get('/home', function () {

        // sendSMS('01751906710', 'Hello, Greetings from Pondit.');

        return view('backend.home');
    })->name('home');

    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    // Category
    Route::get('categories/export/', [CategoryController::class, 'export'])->name('categories.export');
    Route::get('categories/pdf/', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');
    Route::get('/trashed-categories', [CategoryController::class, 'trash'])
        ->name('categories.trashed')->middleware('age_checker');
    Route::get('/trashed-categories/{category}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/trashed-categories/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);
   
    //Product
    Route::resource('products', ProductController::class);
    
    // User
    Route::get('users/export/', [UserController::class, 'export'])->name('users.export');
    Route::get('users/pdf/', [UserController::class, 'downloadPdf'])->name('users.pdf');
    Route::get('/trashed-users', [UserController::class, 'trash'])
        ->name('users.trashed')->middleware('age_checker');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    Route::get('/users/edit-profile', [ProfileController::class, 'edit'])->name('users.profile.edit');

    Route::patch('/users/update-profile', [ProfileController::class, 'update'])->name('users.profile.update');

    Route::resource('users', UserController::class)->except(
        ['create', 'store']
    );

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ProductExport;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use App\Models\Tag;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Image;
use Excel;
use PDF;

class ProductController extends Controller
{
    public function index()
    {

        $productsCollection = Product::latest();

        if (request('search')) {
            $productsCollection = $productsCollection
                ->where('description', 'like', '%' . request('search') . '%')
                ->orWhere('title', 'like', '%' . request('search') . '%');
        }

        $products = $productsCollection->paginate(10);

        return view('backend.products.index', [
            'products' => $products
        ]);
    }

    public function create()
    {

        $tags = Tag::orderBy('name', 'asc')
            ->pluck('name', 'id')
            ->toArray();

        $categories = Category::orderBy('title', 'asc')
            ->pluck('title', 'id')
            ->toArray();

        return view('backend.products.create', compact('categories', 'tags'));
    }

    public function store(Request $request)
    {
        try {

            $product = Product::create([
                'category_id' => $request->category_id,
                'title' => $request->title,
                'description' => $request->description,
                'image' => $this->uploadImage(request()->file('image'))
            ]);

            $product->tags()->attach($request->tag_id);

            return redirect()->route('products.index')->withMessage('Successfully Created!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function show(Product $product)
    {
        dd($product->tags);
        return view('backend.products.show', [
            'product' => $product
        ]);
    }

    public function edit(Product $product)
    {
        return view('backend.products.edit', [
            'product' => $product
        ]);
    }

    public function update(Request $request, Product $product)
    {
        try {
            $requestData = [
                'category_id' => $request->category_id,
                'title' => $request->title,
                'description' => $request->description,
            ];

            if ($request->hasFile('image')) {
                $requestData['image'] = $this->uploadImage(request()->file('image'));
            }

            $product->update($requestData);

            return redirect()->route('products.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy(Product $product)
    {
        try {
            $product->delete();
            return redirect()->route('products.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    // Softdelete
    public function trash()
    {
        $products = Product::onlyTrashed()->get();

        return view('backend.products.trashed', [
            'products' => $products
        ]);
    }

    public function restore($id)
    {
        $product = Product::onlyTrashed()->findOrFail($id);
        $product->restore();
        return redirect()->route('products.trashed')->withMessage('Successfully Restored!');
    }

    public function delete($id)
    {
        $product = Product::onlyTrashed()->findOrFail($id);
        $product->forceDelete();
        return redirect()->route('products.trashed')->withMessage('Successfully Deleted Permanently!');
    }

    public function uploadImage($file)
    {
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        Image::make($file)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/products/' . $fileName);
        return $fileName;
    }

    public function export()
    {
        return Excel::download(new ProductExport, 'products.xlsx');
    }

    public function downloadPdf()
    {
        $products = Product::all();
        $pdf = PDF::loadView('backend.products.pdf', compact('products'));
        return $pdf->download('products.pdf');
    }
}

resources/views/backend/products/create.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Add Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Products </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Create Product <a class="btn btn-sm btn-info" href="{{ route('products.index') }}">List</a>
        </div>
        <div class="card-body">

            <x-backend.layouts.elements.errors :errors="$errors" />

            <form action="{{ route('products.store') }}" enctype="multipart/form-data" method="post">
                @csrf

                <x-backend.form.field>
                    <select name="category_id" id="category_id" class="form-select">
                        @foreach ($categories as $key=>$value)
                        <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                    </select>
                    <x-backend.form.error name="category_id" />
                </x-backend.form.field>

                <x-backend.form.input name="title" />

                <x-backend.form.textarea name="description" />

                <x-backend.form.input name="image" type="file" />


                @foreach ($tags as $key=>$value)
                <input type="checkbox" name="tag_id[]" value="{{ $key }}"> {{ $value }}
                @endforeach

                <br/>

                <x-backend.form.button>Save</x-backend.form.button>
            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/products/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.update', ['category' => $category->id]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')

                <x-backend.form.input name="title" :value="$category->title" />               
                <x-backend.form.textarea name="description">
                {{ $category->description }}
                </x-backend.form.textarea>

                <x-backend.form.input name="image" type="file" :value="$category->image"/>                

                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/products/index.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Products
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Products </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Products</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Products


            <a class="btn btn-sm btn-info" href="{{ route('products.create') }}">Add New</a>

        </div>
        <div class="card-body">

            <x-backend.layouts.elements.message :message="session('message')" />

            <!-- <table id="datatablesSimple"> -->
            <form method="GET" action="{{ route('products.index') }}">
                <x-backend.form.input style="width: 200px;" name='search' />

            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($products as $product)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $product->title }}</td>
                        <td>{{ $product->description }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{{ route('products.show', ['product' => $product->id]) }}">Show</a>

                            <a class="btn btn-warning btn-sm" href="{{ route('products.edit', ['product' => $product->id]) }}">Edit</a>

                            <form style="display:inline" action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                                @csrf
                                @method('delete')

                                <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>

                            <!-- <a href="{{ route('products.destroy', ['product' => $product->id]) }}" >Delete</a> -->


                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $products->links() }}
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/products/pdf.blade.php
<table id="datatablesSimple" border="1">
    <thead>
        <tr>
            <th>Sl#</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    @php $sl=0 @endphp
        @foreach ($categories as $category)
        <tr>
            <td>{{ ++$sl }}</td>
            <td>{{ $category->title }}</td>
            <td>{{ $category->description }}</td>
            
        </tr>
        @endforeach

    </tbody>
</table>

resources/views/backend/products/show.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Details
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Category Details <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Title: {{ $category->title }}</h3>
            <p>Description: {{ $category->description }}</p>
            <img src="{{ asset('storage/images/'.$category->image) }}" />
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/products/trashed.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Categories <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if (session('message'))
            <div class="alert alert-success">
                <span class="close" data-dismiss="alert">&times;</span>
                <strong>{{ session('message') }}.</strong>
            </div>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>
                        
                            <a class="btn btn-warning btn-sm" href="{{ route('categories.restore', ['category' => $category->id]) }}" >Restore</a>

                            <form style="display:inline" action="{{ route('categories.delete', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete permanently?')" class="btn btn-sm btn-danger" type="submit">Permanent Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>

</x-backend.layouts.master>