routes/web.php
<?php

use App\Http\Controllers\CartController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use App\Mail\OrderShippedEmail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-email', function(){
    $user = auth()->user();
    \Mail::to($user->email)->send(new OrderShippedEmail($user));
});

Route::get('/', [PublicController::class, 'index']);
Route::get('/product-details/{product}', [PublicController::class, 'singleProduct'])->name('product-details');
Route::post('/comments/{id}', [CommentController::class, 'store'])->name('comments.store');
Route::get('products/{product}/add-to-cart', [CartController::class, 'add'])->name('add_to_cart');
Route::get('transaction/create', [TransactionController::class, 'create']);
Route::post('payment-success', [TransactionController::class, 'success']);
Route::post('payment-failed', [TransactionController::class, 'fail']);

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    Route::get('/home', function () {

        // sendSMS('01751906710', 'Hello, Greetings from Pondit.');

        return view('backend.home');
    })->name('home');

    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/{role}', [RoleController::class, 'show'])->name('roles.show');

    // Category
    Route::get('categories/export/', [CategoryController::class, 'export'])->name('categories.export');
    Route::get('categories/pdf/', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');
    Route::get('/trashed-categories', [CategoryController::class, 'trash'])
        ->name('categories.trashed')->middleware('age_checker');
    Route::get('/trashed-categories/{category}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/trashed-categories/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::resource('categories', CategoryController::class);
   
    //Product
    Route::resource('products', ProductController::class);
    
    // User
    Route::get('users/export/', [UserController::class, 'export'])->name('users.export');
    Route::get('users/pdf/', [UserController::class, 'downloadPdf'])->name('users.pdf');
    Route::get('/trashed-users', [UserController::class, 'trash'])
        ->name('users.trashed')->middleware('age_checker');
    Route::get('/trashed-users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('/trashed-users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');

    Route::get('/users/edit-profile', [ProfileController::class, 'edit'])->name('users.profile.edit');

    Route::patch('/users/update-profile', [ProfileController::class, 'update'])->name('users.profile.update');

    Route::resource('users', UserController::class)->except(
        ['create', 'store']
    );

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role(){ //inverse relation
        return $this->belongsTo(Role::class);
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Excel;
use Illuminate\Database\QueryException;
// use Image;
use PDF;

class UserController extends Controller
{
    public function index()
    {

        $usersCollection = User::latest();
        
        if(request('search')){
            $usersCollection = $usersCollection
                                ->where('name', 'like', '%'.request('search').'%')
                                ->orWhere('email', 'like', '%'.request('search').'%');
        }

        $users = $usersCollection->paginate(10);

        return view('backend.users.index', [
            'users' => $users
        ]);
    }

    public function show(User $user)
    {
        return view('backend.users.show', [
            'user' => $user
        ]);
    }

    public function edit(User $user)
    {
        $roles = Role::latest()->get();
        return view('backend.users.edit-role', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    public function update(Request $request, User $user)
    {
        try {

            $requestData = [
                'name' => $request->name,
                'role_id' => $request->role_id
            ];

            $user->update($requestData);

            return redirect()->route('users.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy(User $user)
    {
        try {
            $user->delete();
            return redirect()->route('users.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    // Softdelete
    public function trash()
    {
        $users = User::onlyTrashed()->get();

        return view('backend.users.trashed', [
            'users' => $users
        ]);        
    }

    public function restore($id)
    {
        $user = User::onlyTrashed()->findOrFail($id);
        $user->restore();
        return redirect()->route('users.trashed')->withMessage('Successfully Restored!');
    }

    public function delete($id)
    {
        $user = User::onlyTrashed()->findOrFail($id);
        $user->forceDelete();
        return redirect()->route('users.trashed')->withMessage('Successfully Deleted Permanently!');
    }

    // public function uploadImage($file)
    // {        
    //     $fileName = time().'.'.$file->getClientOriginalExtension();
    //     Image::make($file)
    //             ->resize(200, 200)
    //             ->save(storage_path().'/app/public/images/'.$fileName);
    //     return $fileName;
    // }

    public function export() 
    {
        dd('Under Construction');
        return Excel::download(new UserExport, 'users.xlsx');
    }

    public function downloadPdf()
    {
        $users = User::all();
        $pdf = PDF::loadView('backend.users.pdf', compact('users'));
        return $pdf->download('users.pdf');
    }

}

resources/views/backend/users/create.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Add Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Create Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

           <x-backend.layouts.elements.errors :errors="$errors"/>

            <form action="{{ route('categories.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <x-backend.form.input name="title"/>                
                
                <x-backend.form.textarea name="description" />

                <x-backend.form.input name="image" type="file"/>

                <x-backend.form.button>Save</x-backend.form.button>
            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/users/edit-role.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Users </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit User <a class="btn btn-sm btn-info" href="{{ route('users.index') }}">List</a>
        </div>
        <div class="card-body">

            <x-backend.layouts.elements.errors :errors="$errors" />

            <form action="{{ route('users.update', ['user' => $user->id]) }}" method="post">
                @csrf
                @method('patch')

                <x-backend.form.input name="name" :value="$user->name" />

                <x-backend.form.field>
                    <select name="role_id" id="role_id" class="form-select">
                        @foreach ($roles as $role)
                        <option value="{{ $role->id }}"   {{ $role->id == $user->role_id ? 'selected' : '' }} >{{ $role->name }}</option>
                        @endforeach
                    </select>

                </x-backend.form.field>

                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/users/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Users </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit User <a class="btn btn-sm btn-info" href="{{ route('users.index') }}">List</a>
        </div>
        <div class="card-body">

            <x-backend.layouts.elements.message :message="session('message')" />

            <x-backend.layouts.elements.errors :errors="$errors" />

            <form action="{{ route('users.profile.update') }}" method="post">
                @csrf
                @method('patch')

                <x-backend.form.input name="name" :value="$user->name" />
                <x-backend.form.input type="url" name="github_url" :value="$user->profile->github_url" />
                <x-backend.form.input type="url" name="facebook_url" :value="$user->profile->facebook_url" />
                <x-backend.form.input type="url" name="twitter" :value="$user->profile->twitter" />
                <x-backend.form.textarea name="biodata">
                {{ $user->profile->biodata }}
                </x-backend.form.textarea>

                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/users/index.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Users
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Users </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Users</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Users
            <a class="btn btn-sm btn-primary" href="{{ route('users.export') }}">Excel Export</a>
            <a class="btn btn-sm btn-primary" href="{{ route('users.pdf') }}">PDF Download</a>
            <a class="btn btn-sm btn-danger" href="{{ route('users.trashed') }}">Trashed List</a>

        </div>
        <div class="card-body">

            <x-backend.layouts.elements.message :message="session('message')" />

            <!-- <table id="datatablesSimple"> -->
            <form method="GET" action="{{ route('users.index') }}">
                <x-backend.form.input style="width: 200px;" name='search' />

            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($users as $user)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role->name }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{{ route('users.show', ['user' => $user->id]) }}">Show</a>

                            <a class="btn btn-warning btn-sm" href="{{ route('users.edit', ['user' => $user->id]) }}">Edit</a>

                            <form style="display:inline" action="{{ route('users.destroy', ['user' => $user->id]) }}" method="post">
                                @csrf
                                @method('delete')

                                <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>

                            


                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
            {{ $users->links() }}
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/users/pdf.blade.php
<table id="datatablesSimple" border="1">
    <thead>
        <tr>
            <th>Sl#</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    @php $sl=0 @endphp
        @foreach ($categories as $category)
        <tr>
            <td>{{ ++$sl }}</td>
            <td>{{ $category->title }}</td>
            <td>{{ $category->description }}</td>
            
        </tr>
        @endforeach

    </tbody>
</table>

resources/views/backend/users/show.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Details
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Category Details <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Title: {{ $category->title }}</h3>
            <p>Description: {{ $category->description }}</p>
            <img src="{{ asset('storage/images/'.$category->image) }}" />
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/users/trashed.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Categories <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if (session('message'))
            <div class="alert alert-success">
                <span class="close" data-dismiss="alert">&times;</span>
                <strong>{{ session('message') }}.</strong>
            </div>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>
                        
                            <a class="btn btn-warning btn-sm" href="{{ route('categories.restore', ['category' => $category->id]) }}" >Restore</a>

                            <form style="display:inline" action="{{ route('categories.delete', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete permanently?')" class="btn btn-sm btn-danger" type="submit">Permanent Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>

</x-backend.layouts.master>